version: '3'
services:
  web:
    build: .
    image: moisesapi
    ports:
     - "8000:3000"
    volumes:
      - ./src:/home/app/src:cached
    container_name: 'talentuco'
    restart: unless-stopped
    tty: true
    environment:
      - XDEBUG_CONFIG='remote_host=hostenv'
      - VIRTUAL_HOST=laravel.docker
  db:
    image: mysql:8.0.1
    container_name: sl-db
    ports:
      - "3001:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456789
#Volumes
volumes:
  dbdata:
    driver: local